Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2022-10, with the labels that each got.

#1668 Upgrading googletest to v1.11
  dependencies/lib-gtest/getter/CMakeLists.txt.in
Labels: unittests, build-system

#1672 Script extension points on new merc hired
  src/externalized/scripting/FunctionsLibrary.cc
  src/externalized/scripting/FunctionsLibrary.h
  src/externalized/scripting/ScriptingExtensionsLua.cc
  src/game/Tactical/Merc_Hiring.cc
  src/game/Tactical/Soldier_Create.cc
  src/game/Tactical/Soldier_Profile.cc
Labels: enhancement, modding

#1658 Do not call NPCReachedDestination() for soldiers without a MercProfile
  src/externalized/mercs/MercProfile.cc
  src/game/Tactical/Overhead.h
  src/game/Tactical/Soldier_Control.h
  src/game/Tactical/Soldier_Profile.h
  src/game/Tactical/Soldier_Tile.cc
  src/game/TacticalAI/NPC.cc
Labels: bug
