Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2022-04, with the labels that each got.

#1514 Instructions and credits for the simplified chinese mod
  assets/mods/simplified-chinese-localization/manifest.json
Labels: trivial

#1286 Generate Lua enums from C++ codebase
  CMakeLists.txt
  assets/externalized/scripts/enums.lua
  assets/mods/generous-rebels/data/scripts/main.lua
  dependencies/lib-magic_enum/CMakeLists.txt
  dependencies/lib-magic_enum/getter/CMakeLists.txt.in
  rust/stracciatella/src/config/cli.rs
  rust/stracciatella/src/config/engine_options.rs
  rust/stracciatella_c_api/src/c/config.rs
  src/externalized/scripting/CMakeLists.txt
  src/externalized/scripting/EnumCodeGen.cc
  src/externalized/scripting/EnumCodeGen.h
  src/game/GameSettings.h
  src/game/Strategic/Campaign_Types.h
  src/game/Tactical/Overhead_Types.h
  src/sgp/SGP.cc
Labels: enhancement, modding, externalization

#1520 cmake: rewrite the contributor tracking target
  .mailmap
  cmake/target-rebuild-contributors-list.cmake.in
  contributors.txt
Labels: release

#1522 Fix rare vanilla vehicle bugs
  src/game/Strategic/PreBattle_Interface.cc
  src/game/Tactical/Soldier_Create.cc
  src/game/Tactical/Turn_Based_Input.cc
  src/game/TileEngine/WorldDef.cc
Labels: bug, vanilla
