Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2022-07, with the labels that each got.

#1608 Fix several unrelated issues discovered by Coverity
  src/externalized/DefaultContentManager_unittests.cc
  src/game/Strategic/Strategic_Pathing.cc
  src/game/Tactical/Morale.cc
  src/game/Tactical/Soldier_Ani.cc
Labels: vanilla

#1609 Add integration points to change shop inventories and prices
  src/externalized/scripting/FunctionsLibrary.cc
  src/externalized/scripting/FunctionsLibrary.h
  src/externalized/scripting/ScriptingExtensions.h
  src/externalized/scripting/ScriptingExtensionsLua.cc
  src/game/Tactical/Arms_Dealer_Init.cc
  src/game/Tactical/ShopKeeper_Interface.cc
  src/sgp/Types.h
Labels: enhancement, modding

#1614 Functions to make message boxes in Lua
  src/externalized/scripting/FunctionsLibrary.cc
  src/externalized/scripting/FunctionsLibrary.h
  src/externalized/scripting/ScriptingExtensionsLua.cc
  src/game/Tactical/Dialogue_Control.cc
Labels: enhancement, modding

#1615 Let enemy soldiers climb onto roofs again
  src/game/TileEngine/Buildings.cc
  src/game/TileEngine/WorldDef.cc
Labels: bug, non-vanilla
