Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2023-05, with the labels that each got.

#1823 Changes required for C++20 compatibility
  src/externalized/DefaultContentManager.cc
  src/game/Editor/EditorMercs.cc
  src/game/Editor/Editor_Taskbar_Utils.cc
  src/game/Laptop/AIMFacialIndex.cc
  src/game/Laptop/AIMMembers.cc
  src/game/Laptop/Mercs_Files.cc
  src/game/Laptop/Personnel.cc
  src/game/Strategic/Auto_Resolve.cc
  src/sgp/Types.h
Labels: maintenance

#1826 CMakeLists.txt maintenance
  CMakeLists.txt
  src/sgp/Platform.h
Labels: build-system, maintenance

#1832 Strategic-level modding support (Event, Quests and Facts)
  src/externalized/scripting/FunctionsLibrary.cc
  src/externalized/scripting/FunctionsLibrary.h
  src/externalized/scripting/ScriptingExtensionsLua.cc
  src/game/Strategic/Game_Event_Hook.cc
  src/game/Strategic/Quests.cc
  src/game/Tactical/Campaign.cc
Labels: enhancement, modding
