Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2023-02, with the labels that each got.

#1776 Change return type of four AI-related functions to bool
  src/game/TacticalAI/AI.h
  src/game/TacticalAI/AIInternals.h
  src/game/TacticalAI/AIMain.cc
  src/game/TacticalAI/Movement.cc
Labels: maintenance

#1783 Improve scrolling
  src/sgp/Video.cc
Labels: performance

#1798 HandleTownLoyaltyForNPCRecruitment: no loyalty to increase if we're n…
  src/game/Strategic/Strategic_Town_Loyalty.cc
Labels: bug
