Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2024-08, with the labels that each got.

#2049 Delete Text_Utils.h
  src/game/Utils/Text_Utils.h
Labels: maintenance

#2050 Add missing include guard for SamSiteModel.h [skip ci]
  src/externalized/strategic/SamSiteModel.h
Labels: maintenance

#2051 Lift the MAX_WEAPONS restriction; weapons no longer must have an index < 70
  assets/externalized/items.json
  assets/externalized/weapons.json
  src/externalized/DefaultContentManager.cc
  src/externalized/DefaultContentManagerUT.h
  src/game/SaveLoadGameStates.cc
  src/game/SaveLoadGameStates.h
  src/game/Strategic/StrategicMap_Secrets.cc
  src/game/Strategic/Strategic_Status.cc
  src/game/Strategic/Strategic_Status.h
  src/game/Tactical/ArmsDealerInvInit.cc
  src/game/Tactical/Inventory_Choosing.cc
  src/game/Tactical/Item_Types.h
Labels: enhancement, modding, externalization

#2056 Fix sign-compare warning in NPCQuoteInfo
  src/externalized/DefaultContentManager.cc
  src/externalized/content/NPCQuoteInfo.cc
  src/externalized/content/NPCQuoteInfo.h
  src/game/TacticalAI/NPC.cc
Labels: maintenance

#2057 Clean up ItemModel's deserializer methods
  src/externalized/ItemModel.cc
  src/externalized/ItemModel.h
  src/externalized/MagazineModel.cc
  src/externalized/WeaponModels.cc
Labels: maintenance

#2053 Externalize explosives
  assets/externalized/explosion-animations.json
  assets/externalized/explosives.json
  assets/externalized/items.json
  rust/stracciatella/src/schemas/yaml/explosion-animations.schema.yaml
  rust/stracciatella/src/schemas/yaml/explosives.schema.yaml
  rust/stracciatella/src/schemas/yaml/items.schema.yaml
  rust/stracciatella/src/schemas/yaml/types/base-item.schema.yaml
  rust/stracciatella/src/schemas/yaml/types/item-cursor.schema.yaml
  rust/stracciatella/src/schemas/yaml/weapons.schema.yaml
  src/externalized/CMakeLists.txt
  src/externalized/ContentManager.h
  src/externalized/DefaultContentManager.cc
  src/externalized/DefaultContentManager.h
  src/externalized/ExplosionAnimationModel.cc
  src/externalized/ExplosionAnimationModel.h
  src/externalized/ExplosiveModel.cc
  src/externalized/ExplosiveModel.h
  src/externalized/ItemModel.cc
  src/externalized/ItemModel.h
  src/externalized/MagazineModel.cc
  src/externalized/WeaponModels.cc
  src/game/Tactical/Items.cc
  src/game/Tactical/Keys.cc
  src/game/Tactical/Overhead.cc
  src/game/Tactical/Soldier_Control.cc
  src/game/Tactical/Weapons.cc
  src/game/Tactical/Weapons.h
  src/game/TacticalAI/Attacks.cc
  src/game/TileEngine/Explosion_Control.cc
  src/game/TileEngine/Explosion_Control.h
  src/game/TileEngine/SmokeEffects.cc
  src/game/TileEngine/Tile_Animation.cc
Labels: enhancement, externalization

#2059 Fix mercs refusing to join/renew contract
  src/game/Laptop/AIMMembers.cc
  src/game/Strategic/Merc_Contract.cc
  src/game/Strategic/Strategic.cc
  src/game/Strategic/Strategic_Merc_Handler.cc
  src/game/Tactical/Handle_Items.cc
  src/game/Tactical/Merc_Hiring.cc
  src/game/Tactical/Morale.cc
  src/game/Tactical/Overhead.cc
  src/game/Tactical/SkillCheck.cc
  src/game/Tactical/Soldier_Ani.cc
  src/game/Tactical/Soldier_Profile.cc
  src/game/Tactical/Soldier_Profile.h
  src/game/Tactical/Soldier_Profile_Type.h
Labels: bug, non-vanilla

#2060 Externalize explosive calibres
  assets/externalized/explosive-calibres.json
  assets/externalized/explosives.json
  assets/externalized/weapons.json
  rust/stracciatella/src/schemas/yaml/explosive-calibres.schema.yaml
  rust/stracciatella/src/schemas/yaml/explosives.schema.yaml
  src/externalized/CMakeLists.txt
  src/externalized/ContentManager.h
  src/externalized/DefaultContentManager.cc
  src/externalized/DefaultContentManager.h
  src/externalized/ExplosiveCalibreModel.cc
  src/externalized/ExplosiveCalibreModel.h
  src/externalized/ExplosiveModel.cc
  src/externalized/ExplosiveModel.h
  src/externalized/VanillaWeapons_unittests.cc
  src/externalized/WeaponModels.cc
  src/externalized/WeaponModels.h
  src/game/Tactical/Handle_Items.cc
  src/game/Tactical/Items.cc
  src/game/Tactical/Items.h
  src/game/Tactical/Soldier_Control.cc
  src/game/TacticalAI/Attacks.cc
Labels: enhancement, externalization

#2061 Address HACK000E comments in DisplayTeamStats
  src/game/Laptop/Personnel.cc
Labels: maintenance

#2062 Fix crash in CalcBestThrow
  src/game/TacticalAI/Attacks.cc
Labels: bug

#2064 Fix logic error introduced in the previous commit
  src/game/TacticalAI/Attacks.cc
Labels: bug
