Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2024-11, with the labels that each got.

#2111 Minor cleanup of Physics.cc
  src/game/TileEngine/Physics.cc
Labels: maintenance

#2115 Remove VanillaDataStructures*
  src/game/CMakeLists.txt
  src/game/VanillaDataStructures.h
  src/game/VanillaDataStructures_unittest.cc
Labels: maintenance

#2113 Move building C++ source files down from the top CMakeLists.txt
  CMakeLists.txt
  dependencies/lib-magic_enum/CMakeLists.txt
  src/CMakeLists.txt
  src/externalized/DefaultContentManager.cc
  src/externalized/DefaultContentManager.h
  src/externalized/DefaultContentManagerUT.cc
  src/externalized/DefaultContentManagerUT.h
  src/externalized/Soldier.cc
  src/externalized/VanillaWeapons_unittests.cc
  src/externalized/internals/enums.cc
  src/externalized/internals/enums.h
  src/externalized/ui/Easings.cc
  src/game/Laptop/AIMMembers.cc
  src/game/Laptop/IMP_Begin_Screen.cc
  src/game/SaveLoadGame_unittest.cc
  src/game/Tactical/Soldier_Create.cc
  src/game/Tactical/Soldier_Init_List.cc
  src/game/Utils/Cinematics.cc
  src/launcher/CMakeLists.txt
Labels: build-system

#2117 Remove three header files
  src/game/Credits.cc
  src/game/Credits.h
  src/game/GameInitOptionsScreen.cc
  src/game/GameInitOptionsScreen.h
  src/game/ScreenIDs.h
  src/game/Screens.cc
  src/game/Utils/MapUtility.cc
  src/game/Utils/MapUtility.h
Labels: maintenance

#2127 Fix out of bounds read in SameBuilding
  src/game/TacticalAI/AIUtils.cc
Labels: bug

#2128 Refactor pathfinding through doors
  src/game/Tactical/PathAI.cc
  src/game/Tactical/PathAI.h
Labels: maintenance
