Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2024-09, with the labels that each got.

#2065 Address TODO0009: possible endless loop
  docs/archeology/TODO
  src/game/Editor/Smoothing_Utils.cc
  src/game/Tactical/Overhead.cc
  src/game/TileEngine/TileDef.cc
  src/game/TileEngine/TileDef.h
  src/game/TileEngine/WorldDef.cc
  src/game/TileEngine/WorldMan.cc
  src/game/TileEngine/WorldMan.h
Labels: maintenance

#2063 Extract smoke effects
  assets/externalized/smoke-effects.json
  rust/stracciatella/src/schemas/yaml/smoke-effects.schema.yaml
  src/externalized/ContentManager.h
  src/externalized/DefaultContentManager.cc
  src/externalized/DefaultContentManager.h
  src/externalized/ExplosionAnimationModel.cc
  src/externalized/tactical/CMakeLists.txt
  src/externalized/tactical/SmokeEffectModel.cc
  src/externalized/tactical/SmokeEffectModel.h
  src/game/Tactical/LOS.cc
  src/game/Tactical/OppList.cc
  src/game/Tactical/Overhead.cc
  src/game/Tactical/Soldier_Control.cc
  src/game/TacticalAI/AIUtils.cc
  src/game/TileEngine/Explosion_Control.cc
  src/game/TileEngine/Explosion_Control.h
  src/game/TileEngine/SmokeEffects.cc
  src/game/TileEngine/SmokeEffects.h
Labels: enhancement, externalization

#2067 Add basic support for CMake unity builds
  CMakeLists.txt
  src/externalized/CMakeLists.txt
  src/game/CMakeLists.txt
  src/game/Editor/CMakeLists.txt
  src/game/Laptop/CMakeLists.txt
  src/game/Strategic/CMakeLists.txt
  src/game/Strategic/MapScreen.cc
  src/game/Tactical/CMakeLists.txt
  src/game/Tactical/Dialogue_Control.cc
  src/game/Tactical/Overhead.cc
  src/game/Tactical/Soldier_Control.cc
  src/game/TacticalAI/CMakeLists.txt
  src/game/TileEngine/CMakeLists.txt
  src/game/TileEngine/Isometric_Utils.h
  src/game/TileEngine/Lighting.cc
  src/game/TileEngine/Overhead_Map.cc
  src/game/TileEngine/RenderWorld.cc
  src/game/TileEngine/Smell.h
  src/sgp/Button_System.cc
  src/sgp/CMakeLists.txt
  src/sgp/HImage.cc
  src/sgp/WCheck.h
Labels: build-system

#2076 Change the way we initialize WeaponModel instances
  src/externalized/WeaponModels.cc
  src/externalized/WeaponModels.h
Labels: maintenance

#2079 Fix crashing due to missing script records
  src/game/TacticalAI/NPC.cc
Labels: bug, modding

#2081 Add internalName property to TownModel and other fixes
  assets/externalized/CHANGELOG.md
  assets/externalized/script-records-NPCs.json
  assets/externalized/strategic-map-towns.json
  assets/externalized/strategic-mines.json
  assets/externalized/strings/strategic-map-town-name-locatives-rus.json
  rust/stracciatella/src/schemas/yaml/mercs-profiles.schema.yaml
  rust/stracciatella/src/schemas/yaml/strategic-map-towns.schema.yaml
  rust/stracciatella/src/schemas/yaml/strategic-mines.schema.yaml
  rust/stracciatella/src/schemas/yaml/types/quest-id.schema.yaml
  rust/stracciatella/src/schemas/yaml/types/town.schema.yaml
  src/externalized/ContentManager.h
  src/externalized/DefaultContentManager.cc
  src/externalized/DefaultContentManager.h
  src/externalized/content/NPCQuoteInfo.cc
  src/externalized/content/NPCQuoteInfo.h
  src/externalized/internals/enums.cc
  src/externalized/internals/enums.h
  src/externalized/mercs/MercProfile.cc
  src/externalized/mercs/MercProfile.h
  src/externalized/mercs/MercProfileInfo.cc
  src/externalized/mercs/MercProfileInfo.h
  src/externalized/strategic/MineModel.cc
  src/externalized/strategic/MineModel.h
  src/externalized/strategic/TownModel.cc
  src/externalized/strategic/TownModel.h
  src/game/Strategic/Quests.h
Labels: enhancement, modding, externalization

#2085 Remove workaround for an old SDL bug in ScrollJA2Background
  src/sgp/Video.cc
Labels: performance

#2087 Add a constexpr overload for DirectionInc
  src/game/TileEngine/Isometric_Utils.cc
  src/game/TileEngine/Isometric_Utils.h
Labels: maintenance
