Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2024-06, with the labels that each got.

#2001 Fix hang while displaying FOV debug info
  src/game/Tactical/FOV.cc
Labels: bug, minor, non-vanilla

#2006 Fix jump location validation
  src/game/Tactical/Handle_UI.cc
Labels: bug, vanilla

#1997 Make iCurrentMapSectorZ a reference
  src/game/SaveLoadGame.cc
  src/game/Strategic/MapScreen.cc
  src/game/Strategic/Map_Screen_Interface.cc
  src/game/Strategic/Map_Screen_Interface.h
  src/game/Strategic/Map_Screen_Interface_Bottom.cc
  src/game/Strategic/Map_Screen_Interface_Map.cc
  src/game/Strategic/Map_Screen_Interface_Map_Inventory.cc
  src/game/Strategic/Meanwhile.cc
  src/game/Strategic/Strategic_Movement.cc
  src/game/Tactical/Merc_Hiring.cc
  src/game/TileEngine/Radar_Screen.cc
Labels: maintenance

#2017 Fix several compiler warnings
  dependencies/lib-smacker/CMakeLists.txt
  src/game/Laptop/Finances.cc
  src/game/Laptop/History.cc
  src/game/TileEngine/TileDef.cc
  src/game/Utils/Cinematics.cc
Labels: maintenance

#2024 Refactor SearchForClosestMapEdgepoint functions
  src/game/TileEngine/Map_Edgepoints.cc
  src/game/TileEngine/Map_Edgepoints.h
Labels: maintenance
