Repository ja2-stracciatella/ja2-stracciatella, pull requests merged in 2024-05, with the labels that each got.

#1988 Improve loading strings from EDT files
  assets/mods/test-json-dialogs/data/binarydata/aimbios.edt.json
  assets/mods/test-json-dialogs/data/binarydata/help.edt.json
  assets/mods/test-json-dialogs/data/binarydata/mercbios.edt.json
  assets/mods/test-json-dialogs/manifest.json
  src/externalized/ContentManager.h
  src/externalized/DefaultContentManager.cc
  src/externalized/DefaultContentManager.h
  src/externalized/ModPackContentManager.cc
  src/externalized/ModPackContentManager.h
  src/externalized/strings/CMakeLists.txt
  src/externalized/strings/EDT.cc
  src/externalized/strings/EDT.h
  src/externalized/strings/IEDT.h
  src/game/HelpScreen.cc
  src/game/HelpScreenText.h
  src/game/Laptop/AIMMembers.cc
  src/game/Laptop/Mercs_Files.cc
  src/game/Tactical/Dialogue_Control.cc
Labels: proposal, modding, externalization

#1991 Add travelcost values for sliding doors to prevent walking through frame posts
  src/game/TileEngine/WorldDef.cc
Labels: bug, vanilla

#1992 Make our tools less unhappy about LogMessageST
  src/sgp/Logger.h
  src/sgp/Types.h
Labels: maintenance
